//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T9Spelling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T9Spelling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Case #{1}: {2}.
        /// </summary>
        internal static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (or {1} for exit):.
        /// </summary>
        internal static string InputMessageMask {
            get {
                return ResourceManager.GetString("InputMessageMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string has incorrect format..
        /// </summary>
        internal static string InputStringHasIncorrectFormat {
            get {
                return ResourceManager.GetString("InputStringHasIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the string must be between {0} and {1}..
        /// </summary>
        internal static string LengthOfStringMustBeBetween {
            get {
                return ResourceManager.GetString("LengthOfStringMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines in the source file is less than minimum allowed value..
        /// </summary>
        internal static string NumberOfLinesInSourceFileIsLessThanMinimumAllowedValue {
            get {
                return ResourceManager.GetString("NumberOfLinesInSourceFileIsLessThanMinimumAllowedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines in the source file must be between {0} and {1}..
        /// </summary>
        internal static string NumberOfLinesInSourceFileMustBeBetween {
            get {
                return ResourceManager.GetString("NumberOfLinesInSourceFileMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input path to the destination file.
        /// </summary>
        internal static string PleaseInputPathToDestinationFile {
            get {
                return ResourceManager.GetString("PleaseInputPathToDestinationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input path to the source file.
        /// </summary>
        internal static string PleaseInputPathToSourceFile {
            get {
                return ResourceManager.GetString("PleaseInputPathToSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string has incorrect format. Processing is stopped..
        /// </summary>
        internal static string ProcessingIsStopped {
            get {
                return ResourceManager.GetString("ProcessingIsStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry doesn&apos;t contain object for {0}.
        /// </summary>
        internal static string RegistryDoesntContainObject {
            get {
                return ResourceManager.GetString("RegistryDoesntContainObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string contains incorrect symbols..
        /// </summary>
        internal static string StringContainsIncorrectSymbols {
            get {
                return ResourceManager.GetString("StringContainsIncorrectSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work is completed..
        /// </summary>
        internal static string WorkIsCompleted {
            get {
                return ResourceManager.GetString("WorkIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your path has incorrect symbols..
        /// </summary>
        internal static string YourPathHasIncorrectSymbols {
            get {
                return ResourceManager.GetString("YourPathHasIncorrectSymbols", resourceCulture);
            }
        }
    }
}
